### ISSUE TITLE
cpu 消耗高

### ISSUE THREAD

**Issue by cmdares** [OXOYO/X-WebDesktop-Vue#11]
整体应用效果非常不错，但是发现，CPU消耗比较大，笔记本风扇狂转。
看看耗费CPU出现在哪个环节，可否优化。
感谢！

**Comment by OXOYO** [comment]
G6 最新版据说性能有较大提升，最近会考虑升级适配。

**Comment by OXOYO** [comment]
最近在规划next，架构方面会有更好的设计，性能应该也会有所提升
