### ISSUE TITLE
窗口里面的内容无法选中复制

### ISSUE THREAD

**Issue by cncp20** [OXOYO/X-WebDesktop-Vue#21]

**Comment by OXOYO** [comment]
是的

**Comment by bipolarmorgan** [comment]
> 是的

HUH? Can you translate that into english for me?

**Comment by OXOYO** [comment]
> > 是的
> 
> HUH? Can you translate that into english for me?

Maybe you can focus on [XOS UI](https://github.com/OXOYO/xos-ui), which is under development and will support I18N in the future.

**Comment by bipolarmorgan** [comment]
I will take a look!
