### ISSUE TITLE
演示页面登陆不进去

### ISSUE THREAD

**Issue by liesauer** [OXOYO/X-WebDesktop-Vue#35]
登录接口无限卡住，直到超时
![image](https://user-images.githubusercontent.com/8676741/188255265-68db4922-070d-4886-9891-aee92510e7f9.png)

**Comment by OXOYO** [comment]
> 登录接口无限卡住，直到超时 ![image](https://user-images.githubusercontent.com/8676741/188255265-68db4922-070d-4886-9891-aee92510e7f9.png)

可以临时用这个地址 http://47.93.49.248/X-WebDesktop-Vue/

**Comment by OXOYO** [comment]
已修复
